version: '3.8'

services:
  db:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: postgres_energy
    environment:
      POSTGRES_DB: postgres        
      POSTGRES_USER: postgres               
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5433"
    expose:
      - "5433"                      
    volumes:
      - pgdata:/var/lib/postgresql/data  

volumes:
  pgdata:

networks:
  app-network:
    name: app-network